version: '3.8'

services:
  timetracker-legacy:
    image: alirizasaral/timetracker:1
    container_name: timetracker-legacy
    networks:
      - timetracker-network

  timetracker-frontend:
    build: .
    container_name: timetracker-frontend
    ports:
      - "8080:8080"
    depends_on:
      - timetracker-legacy
    environment:
      - TIMETRACKER_BASE_URL=http://timetracker-legacy:8080
    networks:
      - timetracker-network

networks:
  timetracker-network:
    driver: bridge